import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/errors/index.ts',
    'src/router/index.ts',
    'src/idempotency/index.ts',
    'src/retry/index.ts',
    'src/testing/index.ts',
    'src/logger/index.ts',
    'src/logger/pino.ts',
    'src/providers/index.ts',
    'src/providers/stripe.ts',
    'src/providers/github.ts',
    'src/providers/shopify.ts',
    'src/providers/twilio.ts',
    'src/providers/slack.ts',
    'src/providers/clerk.ts',
    'src/providers/sendgrid.ts',
    'src/providers/resend.ts',
    'src/providers/linear.ts',
    'src/providers/vercel.ts',
    'src/providers/discord.ts',
    'src/providers/lemon-squeezy.ts',
    'src/providers/paddle.ts',
    'src/providers/square.ts',
    'src/providers/mailgun.ts',
    'src/providers/postmark.ts',
    'src/providers/svix.ts',
    'src/adapters/fetch.ts',
    'src/adapters/express.ts',
    'src/adapters/fastify.ts',
    'src/adapters/hono.ts',
    'src/adapters/elysia.ts',
    'src/adapters/next-app.ts',
    'src/adapters/next-pages.ts',
  ],
  format: ['esm'],
  dts: true,
  splitting: true,
  treeshake: true,
  sourcemap: true,
  target: 'es2022',
  clean: true,
});
